### ISSUE TITLE
[`@webext-core/fake-browser`]: Vitest doesnt mock `webextension-polyfill@^0.11.0`

### ISSUE THREAD

**Issue by pnd280** [aklinker1/webext-core#72]
## Description
When using `@webext-core/fake-browser` with Vitest, the package fails to properly mock `webextension-polyfill` version `0.11.0` or higher.

## Steps to Reproduce
1. Clone this repository: https://github.com/kayac-chang/webext-core-fake-browser-test (from #43)
2. Update `webextension-polyfill` to `0.11.0` or the latest version `0.12.0`
3. `pnpm test run`
![image](https://github.com/user-attachments/assets/f6ac103b-6948-44a5-a74e-a50b5dcf9022)

## Expected Behavior
The test should run successfully with the mocked browser APIs provided by `@webext-core/fake-browser`.

## Actual Behavior
The test fails, indicating that the browser APIs are not properly mocked.

**Comment by aklinker1** [comment]
@pnd280 huh, very weird. This is an issue with Vitest.

Only workaround I found was to use resolutions to ensure on a single version of `webextnsion-polyfill` is in your node_modules:

```
{
  "resolutions": {
    "webextension-polyfill": "0.12.0"
  }
}
```

This fails for newer versions because `@webext-core/storage` depends on 0.10.0 directly:

```sh
$ yarn list webextension-polyfill
├─ @webext-core/storage@1.1.3
│  └─ webextension-polyfill@0.10.0
└─ webextension-polyfill@0.12.0
```

But I'm not sure why Vitest can't handle that. Lots of your dependencies are out of date, try upgrading everything as well.

**Comment by pnd280** [comment]
@aklinker1 Thank you for the workaround!
